apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery-worker
  template:
    metadata:
      labels:
        app: celery-worker
    spec:
      containers:
      - name: celery-worker
        image: treebyy/celery_rabbitmq:latest
        command: ["celery", "-A", "app.celery_app.celery_app", "worker", "--loglevel=info", "-P", "solo"]